version: "4.3"
services:
    web:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - db
        env_file:
            - ./.env
        volumes:
            - .:/app
    db:
        image: postgres:16.3-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=contacts_app
        expose:
            - "5432"
        ports:
            - "5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
